-------------------	A D M I N I S T R A R     S I S T E M A     M O D I F I C A C I O N    U S U A R I O	-------------------
--OPCION 2: HORARIOS
--OPCION 2.1: SI ELIJE ELIMINAR HORARIO
-- y TBL_HORARIOS_X_EMPLEADO (si elije cambiar horario o eliminarlo)
CREATE OR REPLACE FUNCTION "PERMISOS".F_ELIMINAR_HORARIO_ASIGNADO_EMPL(IN P_ID_EMPLEADO CHARACTER VARYING(10),
								       IN P_TIPO_HORARIO CHARACTER VARYING(60)) 
RETURNS VOID AS $$
DECLARE
 v_id_tipo_horario integer;
BEGIN
	--Obtener el id del tipo de horario a eliminar
	SELECT A."ID_TIPO_HORARIO"
	INTO v_id_tipo_horario
	FROM "PERMISOS"."TBL_TIPOS_HORARIOS" A
	WHERE A."TIPO_HORARIO" = P_TIPO_HORARIO;
	 
	DELETE FROM "PERMISOS"."TBL_HORARIOS_X_EMPLEADO"
	WHERE "ID_EMPLEADO" = P_ID_EMPLEADO AND "ID_TIPO_HORARIO" =  v_id_tipo_horario;
END;
$$ LANGUAGE 'plpgsql';

--Ejecutar función
SELECT * FROM "PERMISOS".F_ELIMINAR_HORARIO_ASIGNADO_EMPL('000028', 'HORARIO GENERAL');