--Ver permisos que ha aprobado el jefe, sin embargo estos puede ser que por el momento no han sido aprobados por el jefe de personal.
CREATE OR REPLACE FUNCTION "PERMISOS".F_VER_PERMISOS_OTORGADOS(IN P_ID_JEFE CHARACTER VARYING(10),
								OUT P_NOMBRE_EMPLEADO TEXT,
								OUT P_TIPO_AUSENCIA CHARACTER VARYING(70),
								OUT P_FECHA_SOLICITUD TIMESTAMP WITHOUT TIME ZONE,
								OUT P_FECHA_INICIO TIMESTAMP WITHOUT TIME ZONE,
								OUT P_FECHA_FIN TIMESTAMP WITHOUT TIME ZONE) 
RETURNS SETOF RECORD AS 
$BODY$
 BEGIN
 RETURN query SELECT CONCAT(B."PRIMER_SEGUNDO_NOMBRE", ' ', B."PRIMER_SEGUNDO_APELLIDO") AS NOMBRE_EMPLEADO, 
			C."TIPO_AUSENCIA",
			A."FECHA_SOLICITUD",
			A."FECHA_INICIO",
			A."FECHA_FIN"
		FROM "PERMISOS"."TBL_PERMISOS" A
		INNER JOIN "PERMISOS"."TBL_EMPLEADOS" B
		ON(A."ID_EMPLEADO" = B."ID_EMPLEADO")
		INNER JOIN "PERMISOS"."TBL_TIPOS_AUSENCIAS" C
		ON(A."ID_TIPO_AUSENCIA" = C."ID_TIPO_AUSENCIA")
		WHERE A."ID_JEFE" = P_ID_JEFE AND A."ESTADO_JEFE" = TRUE AND A."F_CAMBIO_ESTADO_JEFE" IS NOT NULL 
			AND "ESTADO_REVERTIR_PERMISO" = FALSE
		ORDER BY A."F_CAMBIO_ESTADO_JEFE" DESC;
 END;
$BODY$ 
LANGUAGE 'plpgsql';

SELECT * FROM "PERMISOS".F_VER_PERMISOS_OTORGADOS('000001');