-------------------	A D M I N I S T R A R     S I S T E M A 	T I P O S     D E      P E R M I S O S		-------------------
--Muestra los campos según el tipo de ausencia seleccionado
CREATE OR REPLACE FUNCTION "PERMISOS".F_MOSTRAR_ESPECIF_TIPO_PERMISO_A_MODIFICAR(IN P_ID_TIPO_AUSENCIA INTEGER, 
								   OUT P_TIPO_AUSENCIA CHARACTER VARYING(60),
								   OUT P_GOZA_SUELDO BOOLEAN,
								   OUT P_TIEMPO_MAXIMO_HORAS INTEGER, 
								   OUT P_TIEMPO_MAXIMO_DIAS INTEGER,
								    OUT P_GUIA CHARACTER VARYING(20)) 
RETURNS SETOF RECORD AS $$
DECLARE
 v_tiempo_maximo_dias integer;
 v_tiempo_maximo_horas integer; 
BEGIN
	SELECT "TIEMPO_MAXIMO_HORAS"
	INTO v_tiempo_maximo_horas
	FROM "PERMISOS"."TBL_TIPOS_AUSENCIAS"
	WHERE "ID_TIPO_AUSENCIA" = P_ID_TIPO_AUSENCIA;
	
	SELECT "TIEMPO_MAXIMO_DIAS"
	INTO v_tiempo_maximo_dias
	FROM "PERMISOS"."TBL_TIPOS_AUSENCIAS"
	WHERE "ID_TIPO_AUSENCIA" = P_ID_TIPO_AUSENCIA;

	IF (v_tiempo_maximo_horas IS NOT NULL) THEN
		RETURN query SELECT "TIPO_AUSENCIA", "GOZA_SUELDO", "TIEMPO_MAXIMO_HORAS", "TIEMPO_MAXIMO_DIAS", 'HORAS'::CHARACTER VARYING
			     FROM "PERMISOS"."TBL_TIPOS_AUSENCIAS"
			     WHERE "ID_TIPO_AUSENCIA" = P_ID_TIPO_AUSENCIA;
		
		ELSE IF(v_tiempo_maximo_dias IS NOT NULL)THEN
			RETURN query SELECT "TIPO_AUSENCIA", "GOZA_SUELDO", "TIEMPO_MAXIMO_HORAS", "TIEMPO_MAXIMO_DIAS", 'DIAS'::CHARACTER VARYING
				     FROM "PERMISOS"."TBL_TIPOS_AUSENCIAS"
				     WHERE "ID_TIPO_AUSENCIA" = P_ID_TIPO_AUSENCIA;
		END IF;
	END IF;
END;
$$ LANGUAGE 'plpgsql';

--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SELECT * FROM "PERMISOS".F_MOSTRAR_ESPECIF_TIPO_PERMISO_A_MODIFICAR(2);
