--Cuando busca al empleado y necesita ver los permisos del mismo.
CREATE OR REPLACE FUNCTION "PERMISOS".F_MOSTRAR_PERMISO(IN P_ID_EMPLEADO CHARACTER VARYING(10),
							OUT P_TIPO_AUSENCIA CHARACTER VARYING(70), 
							OUT P_FECHA_SOLICITUD TIMESTAMP WITHOUT TIME ZONE,
							OUT P_FECHA_INICIO TIMESTAMP WITHOUT TIME ZONE, 
							OUT P_FECHA_FIN TIMESTAMP WITHOUT TIME ZONE,
							OUT P_VEREDICTO CHARACTER VARYING(30)) 
RETURNS SETOF record AS 
$BODY$
 BEGIN
    RETURN query ((SELECT C."TIPO_AUSENCIA", B."FECHA_SOLICITUD", B."FECHA_INICIO", B."FECHA_FIN",'PERMISO APROBADO'::CHARACTER VARYING
			FROM "PERMISOS"."TBL_PERMISOS" B
			INNER JOIN "PERMISOS"."TBL_TIPOS_AUSENCIAS" C
			ON(B."ID_TIPO_AUSENCIA" = C."ID_TIPO_AUSENCIA")
			WHERE B."ID_EMPLEADO" = P_ID_EMPLEADO AND 
			(B."ESTADO_JEFE" = TRUE AND B."F_CAMBIO_ESTADO_JEFE" IS NOT NULL 
			AND B."ESTADO_JPERSONAL" = TRUE AND B."F_CAMBIO_ESTADO_JPERSONAL" IS NOT NULL) 
			AND B."ESTADO_REVERTIR_PERMISO" = FALSE)
		UNION 
		(SELECT E."TIPO_AUSENCIA", D."FECHA_SOLICITUD", D."FECHA_INICIO", D."FECHA_FIN",'PERMISO RECHAZADO'::CHARACTER VARYING
			FROM "PERMISOS"."TBL_PERMISOS" D
			INNER JOIN "PERMISOS"."TBL_TIPOS_AUSENCIAS" E
			ON(D."ID_TIPO_AUSENCIA" = E."ID_TIPO_AUSENCIA")
			WHERE D."ID_EMPLEADO" = P_ID_EMPLEADO AND 
			      D."ESTADO_REVERTIR_PERMISO" = FALSE AND
			((D."ESTADO_JEFE" = TRUE AND D."F_CAMBIO_ESTADO_JEFE" IS NOT NULL 
			AND D."ESTADO_JPERSONAL" = FALSE AND D."F_CAMBIO_ESTADO_JPERSONAL" IS NOT NULL) 
			OR (D."ESTADO_JEFE" = FALSE AND D."F_CAMBIO_ESTADO_JEFE" IS NOT NULL))));
   
 END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar la función
SELECT * 
FROM "PERMISOS".F_MOSTRAR_PERMISO('000028');