-------------------	A D M I N I S T R A R     S I S T E M A 	U S U A R I O	-------------------
CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_HORARIOS() 
RETURNS TABLE(TIPO_HORARIO CHARACTER VARYING(60)) AS 
$BODY$
 BEGIN
 RETURN query SELECT "TIPO_HORARIO"
	      FROM "PERMISOS"."TBL_TIPOS_HORARIOS";
 END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar función
SELECT * FROM "PERMISOS".F_LISTA_HORARIOS();