CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_JEFES(IN P_ID_EMPLEADO CHARACTER VARYING(10)) 
RETURNS TABLE(NOMBRE_COMPLETO TEXT) AS 
$BODY$
DECLARE
 v_id_jefe_inm character varying(10);
 BEGIN    

	SELECT B."ID_JEFE" INTO v_id_jefe_inm
	FROM "PERMISOS"."TBL_EMPLEADOS" B
	WHERE B."ID_EMPLEADO" = P_ID_EMPLEADO;

	RETURN query SELECT A."PRIMER_SEGUNDO_NOMBRE" || ' ' || A."PRIMER_SEGUNDO_APELLIDO" AS NOMBRE_COMPLETO
		     FROM "PERMISOS"."TBL_EMPLEADOS" A
		     WHERE A."ID_EMPLEADO" = v_id_jefe_inm;


 END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar función
SELECT * FROM "PERMISOS".F_LISTA_JEFES('000030');