CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_DEPARTAMENTOS() 
RETURNS TABLE(ID_DEPARTAMENTO CHARACTER VARYING, NOMBRE_DEPARTAMENTO CHARACTER VARYING) AS 
$BODY$
 BEGIN
 RETURN query SELECT "ID_DEPARTAMENTO", "NOMBRE_DEPARTAMENTO"
	      FROM "PERMISOS"."TBL_DEPARTAMENTOS";
 END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar función
SELECT * FROM "PERMISOS".F_LISTA_DEPARTAMENTOS();