--Función que recibe el ID_EMPLEADO y devuelve DIAS_SEMANA, HORA_INICIO y HORA_FIN del horario(s).
CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_HORARIOS_ASIGNADOS_EMPLEADO(IN P_ID_EMPLEADO CHARACTER VARYING(10),
	OUT P_DIAS_SEMANA CHARACTER VARYING(30), OUT P_HORA_INICIO TIME WITHOUT TIME ZONE, 
	OUT P_HORA_FIN TIME WITHOUT TIME ZONE) 
RETURNS SETOF RECORD AS 
$BODY$
BEGIN    
    RETURN query SELECT B."DIAS_SEMANA", B."HORA_INICIO", B."HORA_FIN"
		 FROM "PERMISOS"."TBL_HORARIOS_X_EMPLEADO" A
		 INNER JOIN "PERMISOS"."TBL_TIPOS_HORARIOS" B
		 ON(A."ID_TIPO_HORARIO" = B."ID_TIPO_HORARIO")
		 WHERE A."ID_EMPLEADO" = P_ID_EMPLEADO;
END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar la función
SELECT * FROM "PERMISOS".F_LISTA_HORARIOS_ASIGNADOS_EMPLEADO('000028');
