-------------------	A D M I N I S T R A R     S I S T E M A     M O D I F I C A C I O N    U S U A R I O	-------------------
--Lista de Horarios que el empleado no tiene asignado.
CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_NOMBRES_HORARIOS_NO_ASIGNADO_EMPL(IN P_ID_EMPLEADO CHARACTER VARYING(10)) 
RETURNS TABLE(TIPO_HORARIO CHARACTER VARYING) AS $$
BEGIN
	RETURN query
		SELECT "TIPO_HORARIO"
			FROM "PERMISOS"."TBL_TIPOS_HORARIOS"
		EXCEPT
		SELECT B."TIPO_HORARIO"
			FROM "PERMISOS"."TBL_HORARIOS_X_EMPLEADO" A
			INNER JOIN "PERMISOS"."TBL_TIPOS_HORARIOS" B
			ON(A."ID_TIPO_HORARIO" = B."ID_TIPO_HORARIO")
			WHERE A."ID_EMPLEADO" = P_ID_EMPLEADO;
END;
$$ LANGUAGE 'plpgsql';


--Ejecutando la función
SELECT * FROM "PERMISOS".F_LISTA_NOMBRES_HORARIOS_NO_ASIGNADO_EMPL('000028');