CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_EMPLEADOS_DEPTO_REGION(IN P_ID_DEPARTAMENTO CHARACTER VARYING(10),
								     IN P_ID_REGIONAL_MODALIDAD CHARACTER VARYING(2),
								     OUT P_ID_EMPLEADO CHARACTER VARYING(2),
								     OUT P_NOMBRE_EMPLEADO TEXT) 
RETURNS SETOF record AS 
$BODY$
 BEGIN
 RETURN query SELECT "ID_EMPLEADO", CONCAT("PRIMER_SEGUNDO_NOMBRE", ' ', "PRIMER_SEGUNDO_APELLIDO") AS P_NOMBRE_COMPLETO
	      FROM "PERMISOS"."TBL_EMPLEADOS"
	      WHERE "ID_DEPARTAMENTO" = P_ID_DEPARTAMENTO AND "ID_REGIONAL_MODALIDAD" = P_ID_REGIONAL_MODALIDAD;
 END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar función
SELECT * FROM "PERMISOS".F_LISTA_EMPLEADOS_DEPTO_REGION('DPTO CS','TA');