--Módulo de Empleado
--Para la solicitud de permiso.

--DEVUELVE EL NOMBRE TIPO_AUSENCIA, TIEMPO_MAXIMO_DIAS, TIEMPO_MAXIMO_HORAS y un P_GUIA que hace referencia si son días u horas.
CREATE OR REPLACE FUNCTION "PERMISOS".F_LISTA_TIPOS_AUSENCIAS(OUT P_TIPO_AUSENCIA CHARACTER VARYING(70),
		OUT P_TIEMPO_MAXIMO_DIAS INTEGER, OUT P_TIEMPO_MAXIMO_HORAS INTEGER, OUT P_GUIA_HD CHARACTER VARYING(20)) 
RETURNS SETOF RECORD AS 
$BODY$
BEGIN    
    RETURN query ((SELECT A."TIPO_AUSENCIA", A."TIEMPO_MAXIMO_DIAS", A."TIEMPO_MAXIMO_HORAS", 'HORAS'::CHARACTER VARYING
		  FROM "PERMISOS"."TBL_TIPOS_AUSENCIAS" A
		  WHERE A."TIEMPO_MAXIMO_DIAS" IS NULL)
		  UNION(SELECT A."TIPO_AUSENCIA", A."TIEMPO_MAXIMO_DIAS", A."TIEMPO_MAXIMO_HORAS", 'DIAS'::CHARACTER VARYING
		  FROM "PERMISOS"."TBL_TIPOS_AUSENCIAS" A
		  WHERE A."TIEMPO_MAXIMO_HORAS" IS NULL));
 END;
$BODY$ 
LANGUAGE 'plpgsql';

--Ejecutar función
SELECT * FROM "PERMISOS".F_LISTA_TIPOS_AUSENCIAS();