﻿--Funnción para dar de baja a un usuario por medio del ID
--Se tiene que deshabilitar el campo de estado en la tabla de tbl empleados por usuario
CREATE OR REPLACE FUNCTION "PERMISOS".F_DAR_BAJA_USR(IN P_ID_EMPLEADO CHARACTER VARYING(10)) 
RETURNS VOID AS $$
BEGIN
	UPDATE "PERMISOS"."TBL_EMPLEADOS_X_TUSUARIO"
	SET "ESTADO" = FALSE
	WHERE "ID_EMPLEADO" = P_ID_EMPLEADO;

	UPDATE "PERMISOS"."TBL_EMPLEADOS"
	SET "NOMBRE_USUARIO" = null, "CONTRASENIA" = null,"ESTADO_V" = FALSE
	WHERE "ID_EMPLEADO" = P_ID_EMPLEADO;

	DELETE FROM "PERMISOS"."TBL_HORARIOS_X_EMPLEADO"
	WHERE "ID_EMPLEADO" = P_ID_EMPLEADO;

END;
$$ LANGUAGE 'plpgsql';

--Ejecutar
SELECT * FROM "PERMISOS".F_DAR_BAJA_USR('000002');