-------------------	A D M I N I S T R A R     S I S T E M A 	H O R A R I O S		-------------------
--Muestra los campos según el horario seleccionado
CREATE OR REPLACE FUNCTION "PERMISOS".F_MOSTRAR_ESPECIF_HORARIO_A_MODIFICAR(IN P_ID_TIPO_HORARIO INTEGER, 
								   OUT P_TIPO_HORARIO CHARACTER VARYING(60),
								   OUT P_DIAS_SEMANA CHARACTER VARYING(30),
								   OUT P_HORA_INICIO TIME WITHOUT TIME ZONE, 
								   OUT P_HORA_FIN TIME WITHOUT TIME ZONE) 
RETURNS SETOF RECORD AS $$
BEGIN
	RETURN query SELECT A."TIPO_HORARIO", A."DIAS_SEMANA", A."HORA_INICIO", A."HORA_FIN"
			FROM "PERMISOS"."TBL_TIPOS_HORARIOS" A
			WHERE A."ID_TIPO_HORARIO" = P_ID_TIPO_HORARIO;
END;
$$ LANGUAGE 'plpgsql';

--+++++++++++++++++++++++++++++++++++++++++++++++++++++++
SELECT * FROM "PERMISOS".F_MOSTRAR_ESPECIF_HORARIO_A_MODIFICAR(1);